name: Tree-sitter parser setup
description: Set up a tree-sitter parser repo

branding:
  color: green
  icon: settings

inputs:
  fetch-depth:
    description: Repository fetch depth
    default: "2"
  submodules:
    description: Initialize submodules
    default: "false"
  tree-sitter-ref:
    description: A tree-sitter commit, tag, or branch
    default: latest

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: ${{inputs.fetch-depth}}
        submodules: ${{inputs.submodules}}
    - name: Install tree-sitter CLI
      uses: tree-sitter/setup-action/cli@v1
      with:
        tree-sitter-ref: ${{inputs.tree-sitter-ref}}
